sudo: required
dist: trusty
services: docker
language: cpp
python:
- '3.4'
cache:
  timeout: 600

cache:
  - pip
  - apt

addons:
  apt:
    packages:
    - git
    - python3
    - python3-pip

########################
########################
jobs:
  include:
  ######################## XENIAL - TESTS
  - stage: build+test
    os: linux
    env:
    - CMAKE_ARGS='-DBUILD_TESTS=ON'
    - TEST='TRUE'
    - CC_VER="5"
    - PLATFORM='xenial'
    script: "./travis/build.sh"

  ######################## XENIAL - Python
  - stage: build+test
    os: linux
    env:
    - CMAKE_ARGS='-DBUILD_PYTHON=ON'
    - TEST='TRUE'
    - CC_VER="5"
    - PLATFORM='xenial'
    script: "./travis/build.sh"

#  ######################## XENIAL-EMSCRIPTEN
#  - stage: build+test
#    os: linux
#    env:
#    - PLATFORM='xenial-emscripten'
#    script: "./travis/build.sh"
#
#  ######################## OSX + TESTS
#  - stage: build+test
#    os: osx
#    if: branch = master
#    env:
#    - CMAKE_ARGS='-DBUILD_TESTS=ON'
#    - TEST='TRUE'
#    script:
#    - "./travis/build.sh"

  ######################## OSX
  - stage: build+test
    os: osx
    if: branch = master
    env:
    - CMAKE_ARGS='-DBUILD_PYTHON=ON'
    script:
    - "./travis/build.sh"
#
#  ########################
#  - stage: test_deployment
#    script: echo "TODO..."

  ########################
  - stage: publish
    if: tag =~ ^v
    os: linux
    env:
    - CC_VER="5"
    - PLATFORM='xenial'
    - DEPLOY='TRUE'
    script:
    - sudo pip3 install -U pip setuptools twine
    - "./travis/build.sh"

    deploy:
      provider: pypi
      skip_cleanup: true
      user: jleni
      password:
        secure: VvApoJkjRbGGlGioo5743Vn/U5//NZ5yd0Ql1SwVL6L08tRHh7nOQizvizc/2ybtgZTZ3s9ewwqLMEGOnIIFfjPN8N5vTJjndrOolVYC2ZaYim0hLc5ova9dswXUfFlKWDiKGvXSNc2napIUgp/kHolHt9ulSw1z5QGLE4dBJl9GyKybnUKaprEPLBVu2zxJaDm0RoBcy0PQIRJyRIa3sP29hrD+EfnywfGiaBGah+xashWOuEQhyrALqLvFgpiOpuoNsT4/zfMUl8k8YAUDhg1a54RAXzHJ4DwMECoRMfB8YD53knvwfeaxtawgD8eXzvY4phU/pWgPG4VyiiuRl2eIqxgYlAiGnNXuZA5IHwFgnc3ku6vVArANC+XGR6QU2BllZiSCWxZyplAQ7dLxQDcrP/AzZ8t+2MKQhwAoHIUsshIox3Mc9vBUJhGv75AMpm3Lai1/IGA8ExDGBiEMLYEOXI+hPI/hnHoLpKOE19zYqa5OxGPb37VFkTP8OrB0Pb7x8j1IY4CTamLRQvYX2XTExLvHS0+KUtEUn688ti6Fid5dU6HR0oFLHuo6NqEH7yHPjhdoj4tBYb32hgujFsIYdqpY/4e/2zDtRyExdDLpHytKkv668JCs9NREBIh71XDi/wfhtYmi3ck5LGD9x4Ikq9qVl2wlfcnw5rl4O0k=
      on:
        tags: true
        all_branches: true

#  ########################
#  - stage: publish
#    if: tag =~ ^v
#    os: linux
#    env:
#    - PLATFORM='xenial-emscripten'
#    script:
#    - "./travis/build.sh"
#    - "./travis/patch_npmversion.sh"
#
#    before_deploy: npm version
#
#    deploy:
#      provider: npm
#      skip_cleanup: true
#      email: "info@theqrl.org"
#      api_key: $NPM_API_KEY
#      on:
#        tags: true
#        all_branches: true
